fin_report_realise = {'result':
                          {'header': {'num': '5781417', 'doc_date': '2024-01-31', 'start_date': '2024-01-01',
                                      'stop_date': '2024-01-31',
                                      'contract_date': '2022-06-22', 'contract_num': 'ИР-124012/22',
                                      'payer_name': 'Интернет Решения, ООО',
                                      'payer_inn': '7704217370', 'payer_kpp': '997750001', 'rcv_name': 'ООО "АРТОЛЬ"',
                                      'rcv_inn': '6234113064',
                                      'rcv_kpp': '623401001', 'doc_amount': 165833.15, 'vat_amount': 27638.8583,
                                      'currency_code': 'RUR'},
                           'rows': [{'row_number': 1, 'product_id': 490790448,
                                     'product_name': 'ИО 102-29 "Эстет-сейф" инвентор',
                                     'offer_id': 'Io10229AstetSeifInvertor', 'barcode': 'OZN936299956', 'price': 749,
                                     'commission_percent': 0.165, 'price_sale': 756, 'sale_qty': 1, 'sale_amount': 756,
                                     'sale_discount': 0,
                                     'sale_commission': 130.59, 'sale_price_seller': 625.41, 'return_sale': 0,
                                     'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 2, 'product_id': 490790436,
                                     'product_name': 'Ио 102-40 исп. Б2П (2) ТЕРРАКОТОВЫЙ пластмассовый рукав',
                                     'offer_id': 'Io10240ispB2P2TerrakotPlastmRukav', 'barcode': 'OZN936300103',
                                     'price': 339,
                                     'commission_percent': 0.165, 'price_sale': 336, 'sale_qty': 1, 'sale_amount': 336,
                                     'sale_discount': 0,
                                     'sale_commission': 52.94, 'sale_price_seller': 283.06, 'return_sale': 0,
                                     'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 3, 'product_id': 490779437,
                                     'product_name': 'Сирин Exd-УФ-М извещатель пожарный пламени',
                                     'offer_id': '1495', 'barcode': 'OZN937572125', 'price': 39815,
                                     'commission_percent': 0.165,
                                     'price_sale': 34619, 'sale_qty': 2, 'sale_amount': 69238, 'sale_discount': 0,
                                     'sale_commission': 2746.96,
                                     'sale_price_seller': 66491.04, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 4, 'product_id': 490779238, 'product_name': 'Астра-321 (ИО 101-7)',
                                     'offer_id': 'Astra1017',
                                     'barcode': 'OZN937573990', 'price': 579, 'commission_percent': 0.165,
                                     'price_sale': 565, 'sale_qty': 1,
                                     'sale_amount': 565, 'sale_discount': 0, 'sale_commission': 81.54,
                                     'sale_price_seller': 483.46,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 5, 'product_id': 490779253,
                                     'product_name': 'ИО 102-50 исп. Б2П (2) пластмассовый рукав',
                                     'offer_id': 'IO10250ispB2PplastmRukav', 'barcode': 'OZN937590817', 'price': 330,
                                     'commission_percent': 0.165, 'price_sale': 330, 'sale_qty': 1, 'sale_amount': 330,
                                     'sale_discount': 0,
                                     'sale_commission': 54.45, 'sale_price_seller': 275.55, 'return_sale': 0,
                                     'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 6, 'product_id': 490779224,
                                     'product_name': 'ИО 102-50 исп. Б2П (3) металлический рукав',
                                     'offer_id': 'IO10250ispB2P3MetalRukav', 'barcode': 'OZN937592161', 'price': 359,
                                     'commission_percent': 0.165, 'price_sale': 366, 'sale_qty': 1, 'sale_amount': 366,
                                     'sale_discount': 0,
                                     'sale_commission': 66.24, 'sale_price_seller': 299.76, 'return_sale': 366,
                                     'return_qty': 1,
                                     'return_amount': 366, 'return_discount': 0, 'return_commission': 66.24,
                                     'return_price_seller': 299.76},
                                    {'row_number': 7, 'product_id': 490790409, 'product_name': 'Водолей-Р (02)',
                                     'offer_id': 'VodoleiP02',
                                     'barcode': 'OZN937649296', 'price': 919, 'commission_percent': 0.145,
                                     'price_sale': 792, 'sale_qty': 1,
                                     'sale_amount': 792, 'sale_discount': 0, 'sale_commission': 6.26,
                                     'sale_price_seller': 785.74,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 8, 'product_id': 490790382,
                                     'product_name': 'ИО 102-40 исп. Б3П (3) металлический рукав',
                                     'offer_id': 'Io10240ispbzp3', 'barcode': 'OZN937649301', 'price': 599,
                                     'commission_percent': 0.165,
                                     'price_sale': 581, 'sale_qty': 1, 'sale_amount': 581, 'sale_discount': 0,
                                     'sale_commission': 80.84,
                                     'sale_price_seller': 500.16, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 9, 'product_id': 490790382,
                                     'product_name': 'ИО 102-40 исп. Б3П (3) металлический рукав',
                                     'offer_id': 'Io10240ispbzp3', 'barcode': 'OZN937649301', 'price': 599,
                                     'commission_percent': 0.165,
                                     'price_sale': 543, 'sale_qty': 1, 'sale_amount': 543, 'sale_discount': 0,
                                     'sale_commission': 42.84,
                                     'sale_price_seller': 500.16, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 10, 'product_id': 490790382,
                                     'product_name': 'ИО 102-40 исп. Б3П (3) металлический рукав',
                                     'offer_id': 'Io10240ispbzp3', 'barcode': 'OZN937649301', 'price': 599,
                                     'commission_percent': 0.165,
                                     'price_sale': 608, 'sale_qty': 1, 'sale_amount': 608, 'sale_discount': 0,
                                     'sale_commission': 107.84,
                                     'sale_price_seller': 500.16, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 11, 'product_id': 490790382,
                                     'product_name': 'ИО 102-40 исп. Б3П (3) металлический рукав',
                                     'offer_id': 'Io10240ispbzp3', 'barcode': 'OZN937649301', 'price': 599,
                                     'commission_percent': 0.145,
                                     'price_sale': 569, 'sale_qty': 1, 'sale_amount': 569, 'sale_discount': 0,
                                     'sale_commission': 56.86,
                                     'sale_price_seller': 512.14, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 12, 'product_id': 490790359,
                                     'product_name': 'КНС исп.А (ИО 101-1(А)',
                                     'offer_id': 'Knsispaio1011a', 'barcode': 'OZN937649332', 'price': 699,
                                     'commission_percent': 0.165,
                                     'price_sale': 723, 'sale_qty': 3, 'sale_amount': 2169, 'sale_discount': 0,
                                     'sale_commission': 418.02,
                                     'sale_price_seller': 1750.98, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 13, 'product_id': 490790350,
                                     'product_name': 'ИО 102-40 исп. А2П (3) металлический рукав',
                                     'offer_id': 'Io10240A2P3MetalRukav', 'barcode': 'OZN937649437', 'price': 395,
                                     'commission_percent': 0.165,
                                     'price_sale': 452, 'sale_qty': 2, 'sale_amount': 904, 'sale_discount': 0,
                                     'sale_commission': 244.36,
                                     'sale_price_seller': 659.64, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 14, 'product_id': 493042649, 'product_name': 'ИП 212-69/3М с АКБ',
                                     'offer_id': 'ip212-69/3M', 'barcode': 'OZN937818406', 'price': 740,
                                     'commission_percent': 0.165,
                                     'price_sale': 679, 'sale_qty': 1, 'sale_amount': 679, 'sale_discount': 0,
                                     'sale_commission': 61.1,
                                     'sale_price_seller': 617.9, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 15, 'product_id': 493037634, 'product_name': 'ЭРа-500',
                                     'offer_id': 'Era500',
                                     'barcode': 'OZN937841949', 'price': 16295, 'commission_percent': 0.165,
                                     'price_sale': 13700,
                                     'sale_qty': 1, 'sale_amount': 13700, 'sale_discount': 0, 'sale_commission': 93.68,
                                     'sale_price_seller': 13606.32, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 16, 'product_id': 493042644,
                                     'product_name': 'ИП 105-1 А3 (без ИВС-2)',
                                     'offer_id': 'izveshateli105-1A3', 'barcode': 'OZN937849414', 'price': 599,
                                     'commission_percent': 0.165,
                                     'price_sale': 642, 'sale_qty': 1, 'sale_amount': 642, 'sale_discount': 0,
                                     'sale_commission': 141.84,
                                     'sale_price_seller': 500.16, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 17, 'product_id': 493037609, 'product_name': 'Кварц (вар.1)',
                                     'offer_id': 'KvarcVar1',
                                     'barcode': 'OZN937854933', 'price': 4499, 'commission_percent': 0.165,
                                     'price_sale': 3465, 'sale_qty': 1,
                                     'sale_amount': 3465, 'sale_discount': 291.78, 'sale_commission': 0.12,
                                     'sale_price_seller': 3756.66,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 18, 'product_id': 493051670, 'product_name': 'ББП-50 TS Tantos',
                                     'offer_id': 'BBP50TSTantos', 'barcode': 'OZN937877449', 'price': 2133,
                                     'commission_percent': 0.145, 'price_sale': 1865, 'sale_qty': 1,
                                     'sale_amount': 1865, 'sale_discount': 0, 'sale_commission': 41.29,
                                     'sale_price_seller': 1823.71, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 19, 'product_id': 493063048, 'product_name': 'Багор пожарный',
                                     'offer_id': 'Bagorpojarn',
                                     'barcode': 'OZN937927364', 'price': 899, 'commission_percent': 0.18,
                                     'price_sale': 763, 'sale_qty': 1,
                                     'sale_amount': 763, 'sale_discount': 0, 'sale_commission': 25.82,
                                     'sale_price_seller': 737.18,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 20, 'product_id': 493063048, 'product_name': 'Багор пожарный',
                                     'offer_id': 'Bagorpojarn',
                                     'barcode': 'OZN937927364', 'price': 899, 'commission_percent': 0.18,
                                     'price_sale': 750, 'sale_qty': 2,
                                     'sale_amount': 1500, 'sale_discount': 0, 'sale_commission': 25.64,
                                     'sale_price_seller': 1474.36,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 21, 'product_id': 493063048, 'product_name': 'Багор пожарный',
                                     'offer_id': 'Bagorpojarn',
                                     'barcode': 'OZN937927364', 'price': 899, 'commission_percent': 0.18,
                                     'price_sale': 758, 'sale_qty': 2,
                                     'sale_amount': 1516, 'sale_discount': 0, 'sale_commission': 41.64,
                                     'sale_price_seller': 1474.36,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0}, {'row_number': 22, 'product_id': 490779227,
                                                                 'product_name': 'Кнопка тревожной сигнализации радиоканальная RR-1t',
                                                                 'offer_id': '55465', 'barcode': 'OZN958220646',
                                                                 'price': 2699,
                                                                 'commission_percent': 0.165, 'price_sale': 2199,
                                                                 'sale_qty': 1,
                                                                 'sale_amount': 2199, 'sale_discount': 54.78,
                                                                 'sale_commission': 0.12,
                                                                 'sale_price_seller': 2253.66, 'return_sale': 0,
                                                                 'return_qty': 0,
                                                                 'return_amount': 0, 'return_discount': 0,
                                                                 'return_commission': 0,
                                                                 'return_price_seller': 0},
                                    {'row_number': 23, 'product_id': 490779227,
                                     'product_name': 'Кнопка тревожной сигнализации радиоканальная RR-1t',
                                     'offer_id': '55465', 'barcode': 'OZN958220646',
                                     'price': 2699, 'commission_percent': 0.165,
                                     'price_sale': 2259, 'sale_qty': 1,
                                     'sale_amount': 2259, 'sale_discount': 0,
                                     'sale_commission': 5.34,
                                     'sale_price_seller': 2253.66, 'return_sale': 0,
                                     'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 24, 'product_id': 490779444,
                                     'product_name': 'Извещатель охранный точечный магнитоконтактный Ио 102-54',
                                     'offer_id': 'IO10254',
                                     'barcode': '', 'price': 249, 'commission_percent': 0.165, 'price_sale': 250,
                                     'sale_qty': 1,
                                     'sale_amount': 250, 'sale_discount': 0, 'sale_commission': 42.09,
                                     'sale_price_seller': 207.91,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 25, 'product_id': 493039068,
                                     'product_name': 'Пульт программирования универсальный с USB',
                                     'offer_id': 'PultProgrammirovaniyUniversalnuisUSB', 'barcode': 'OZN958865810',
                                     'price': 5599,
                                     'commission_percent': 0.165, 'price_sale': 4738, 'sale_qty': 1,
                                     'sale_amount': 4738, 'sale_discount': 0,
                                     'sale_commission': 62.84, 'sale_price_seller': 4675.16, 'return_sale': 0,
                                     'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 26, 'product_id': 493037656,
                                     'product_name': 'Контроллер CCU422-HOME/W/PC',
                                     'offer_id': 'CCU422HOME', 'barcode': 'OZN958904932', 'price': 10399,
                                     'commission_percent': 0.145,
                                     'price_sale': 8545, 'sale_qty': 1, 'sale_amount': 8545, 'sale_discount': 346.26,
                                     'sale_commission': 0.12,
                                     'sale_price_seller': 8891.14, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 27, 'product_id': 493037647,
                                     'product_name': 'Универсальный программируемый пульт Dublicator URC-4 V3.1',
                                     'offer_id': 'DublicatorURC431',
                                     'barcode': 'OZN958907861', 'price': 999,
                                     'commission_percent': 0.165, 'price_sale': 864,
                                     'sale_qty': 1, 'sale_amount': 864, 'sale_discount': 0,
                                     'sale_commission': 29.84, 'sale_price_seller': 834.16,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 28, 'product_id': 493037647,
                                     'product_name': 'Универсальный программируемый пульт Dublicator URC-4 V3.1',
                                     'offer_id': 'DublicatorURC431', 'barcode': 'OZN958907861', 'price': 999,
                                     'commission_percent': 0.165,
                                     'price_sale': 882, 'sale_qty': 1, 'sale_amount': 882, 'sale_discount': 0,
                                     'sale_commission': 47.84,
                                     'sale_price_seller': 834.16, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 29, 'product_id': 493037647,
                                     'product_name': 'Универсальный программируемый пульт Dublicator URC-4 V3.1',
                                     'offer_id': 'DublicatorURC431',
                                     'barcode': 'OZN958907861', 'price': 1599,
                                     'commission_percent': 0.165, 'price_sale': 1599,
                                     'sale_qty': 1, 'sale_amount': 1599,
                                     'sale_discount': 0, 'sale_commission': 263.84,
                                     'sale_price_seller': 1335.16, 'return_sale': 0,
                                     'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 30, 'product_id': 490790347,
                                     'product_name': 'ИО 102-29 "Эстет-сейф"',
                                     'offer_id': 'Io10229AstetSeif', 'barcode': 'OZN962978533', 'price': 1199,
                                     'commission_percent': 0.165,
                                     'price_sale': 1225, 'sale_qty': 2, 'sale_amount': 2450, 'sale_discount': 0,
                                     'sale_commission': 447.68,
                                     'sale_price_seller': 2002.32, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 31, 'product_id': 493051665,
                                     'product_name': 'Блок питания стабилизированный Бп АТ-12/50',
                                     'offer_id': '7465', 'barcode': 'OZN963020722', 'price': 2049,
                                     'commission_percent': 0.145,
                                     'price_sale': 1729, 'sale_qty': 2, 'sale_amount': 3458, 'sale_discount': 46.02,
                                     'sale_commission': 0.24,
                                     'sale_price_seller': 3503.78, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 32, 'product_id': 493051665,
                                     'product_name': 'Блок питания стабилизированный Бп АТ-12/50',
                                     'offer_id': '7465', 'barcode': 'OZN963020722', 'price': 2049,
                                     'commission_percent': 0.145,
                                     'price_sale': 1736, 'sale_qty': 1, 'sale_amount': 1736, 'sale_discount': 16.01,
                                     'sale_commission': 0.12,
                                     'sale_price_seller': 1751.89, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 33, 'product_id': 493051665,
                                     'product_name': 'Блок питания стабилизированный Бп АТ-12/50',
                                     'offer_id': '7465', 'barcode': 'OZN963020722', 'price': 2049,
                                     'commission_percent': 0.145,
                                     'price_sale': 1784, 'sale_qty': 1, 'sale_amount': 1784, 'sale_discount': 0,
                                     'sale_commission': 32.11,
                                     'sale_price_seller': 1751.89, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 34, 'product_id': 493051669,
                                     'product_name': 'Источник стабилизированного питания БП АТ-12/30',
                                     'offer_id': '34568', 'barcode': 'OZN963021582',
                                     'price': 1799, 'commission_percent': 0.145,
                                     'price_sale': 1577, 'sale_qty': 1,
                                     'sale_amount': 1577, 'sale_discount': 0,
                                     'sale_commission': 38.86,
                                     'sale_price_seller': 1538.14, 'return_sale': 0,
                                     'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 35, 'product_id': 571100090,
                                     'product_name': 'Камера видеонаблюдения ST-1006 (2,8-12)',
                                     'offer_id': 'ST10062812', 'barcode': 'OZN1076283110', 'price': 2199,
                                     'commission_percent': 0.145,
                                     'price_sale': 1856, 'sale_qty': 1, 'sale_amount': 1856, 'sale_discount': 24.26,
                                     'sale_commission': 0.12,
                                     'sale_price_seller': 1880.14, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 36, 'product_id': 571147019,
                                     'product_name': 'Видеорегистратор SEDVr-6308Av',
                                     'offer_id': 'SEDVR6308AV', 'barcode': 'OZN1076363443', 'price': 3599,
                                     'commission_percent': 0.13,
                                     'price_sale': 0, 'sale_qty': 0, 'sale_amount': 0, 'sale_discount': 0,
                                     'sale_commission': 0,
                                     'sale_price_seller': 0, 'return_sale': 3065, 'return_qty': 1,
                                     'return_amount': 3065,
                                     'return_discount': 66.25, 'return_commission': 0.12,
                                     'return_price_seller': 3131.13},
                                    {'row_number': 37, 'product_id': 571150044,
                                     'product_name': 'Тревожная радиокнопка RR-701t',
                                     'offer_id': 'rr701t', 'barcode': 'OZN1076367725', 'price': 4199,
                                     'commission_percent': 0.165,
                                     'price_sale': 3343, 'sale_qty': 1, 'sale_amount': 3343, 'sale_discount': 163.28,
                                     'sale_commission': 0.12,
                                     'sale_price_seller': 3506.16, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 38, 'product_id': 571188800,
                                     'product_name': 'RR-2P (RR-2P-01) Пульт-программатор',
                                     'offer_id': 'PR2PRR2P01pyltprogrammator', 'barcode': 'OZN1076443832',
                                     'price': 8499,
                                     'commission_percent': 0.165, 'price_sale': 7193, 'sale_qty': 1,
                                     'sale_amount': 7193, 'sale_discount': 0,
                                     'sale_commission': 96.34, 'sale_price_seller': 7096.66, 'return_sale': 0,
                                     'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 39, 'product_id': 610547869, 'product_name': 'Астра-421 РК',
                                     'offer_id': 'astra421',
                                     'barcode': 'OZN1148072497', 'price': 2499, 'commission_percent': 0.165,
                                     'price_sale': 2114, 'sale_qty': 1,
                                     'sale_amount': 2114, 'sale_discount': 0, 'sale_commission': 27.34,
                                     'sale_price_seller': 2086.66,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 40, 'product_id': 610547869, 'product_name': 'Астра-421 РК',
                                     'offer_id': 'astra421',
                                     'barcode': 'OZN1148072497', 'price': 2499, 'commission_percent': 0.165,
                                     'price_sale': 2134, 'sale_qty': 2,
                                     'sale_amount': 4268, 'sale_discount': 0, 'sale_commission': 94.68,
                                     'sale_price_seller': 4173.32,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0}, {'row_number': 41, 'product_id': 614087998,
                                                                 'product_name': 'Delta Battery Аккумуляторная батарейка, 7000 мАч, 1 шт',
                                                                 'offer_id': 'ETALONFORS1207',
                                                                 'barcode': 'OZN1154091180', 'price': 2299,
                                                                 'commission_percent': 0.195, 'price_sale': 1939,
                                                                 'sale_qty': 1,
                                                                 'sale_amount': 1939, 'sale_discount': 0,
                                                                 'sale_commission': 88.31,
                                                                 'sale_price_seller': 1850.69, 'return_sale': 0,
                                                                 'return_qty': 0,
                                                                 'return_amount': 0, 'return_discount': 0,
                                                                 'return_commission': 0,
                                                                 'return_price_seller': 0},
                                    {'row_number': 42, 'product_id': 670838276,
                                     'product_name': 'J2000-DF-Coordinat блок сопряжения координатный',
                                     'offer_id': 'artoldf', 'barcode': 'OZN1237070163',
                                     'price': 1699, 'commission_percent': 0.165,
                                     'price_sale': 1651, 'sale_qty': 1,
                                     'sale_amount': 1651, 'sale_discount': 0,
                                     'sale_commission': 232.34,
                                     'sale_price_seller': 1418.66, 'return_sale': 0,
                                     'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 43, 'product_id': 690826181,
                                     'product_name': 'Видеокамера Polyvision PN-IP2-B2.8 v.2.6.3',
                                     'offer_id': 'tjikl12h', 'barcode': '', 'price': 5999, 'commission_percent': 0.165,
                                     'price_sale': 4924,
                                     'sale_qty': 1, 'sale_amount': 4924, 'sale_discount': 85.28,
                                     'sale_commission': 0.12,
                                     'sale_price_seller': 5009.16, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 44, 'product_id': 714725086,
                                     'product_name': 'Радий УК-ВК/04 устройство коммутационное',
                                     'offer_id': 'grdgrgh4562', 'barcode': '', 'price': 2199,
                                     'commission_percent': 0.115, 'price_sale': 1971,
                                     'sale_qty': 1, 'sale_amount': 1971, 'sale_discount': 0, 'sale_commission': 24.89,
                                     'sale_price_seller': 1946.11, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 45, 'product_id': 779844752,
                                     'product_name': 'Извещатель инфракрасный пассивный ИД-70',
                                     'offer_id': 'riojvc4', 'barcode': '', 'price': 6299, 'commission_percent': 0.165,
                                     'price_sale': 5331,
                                     'sale_qty': 1, 'sale_amount': 5331, 'sale_discount': 0, 'sale_commission': 71.34,
                                     'sale_price_seller': 5259.66, 'return_sale': 0, 'return_qty': 0,
                                     'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 46, 'product_id': 782262479,
                                     'product_name': 'Извещатель охранный точечный '
                                                     'электроконтактный ИО 101-5/1 '
                                                     '"Черепаха-1М"',
                                     'offer_id': 'Io10151', 'barcode': '', 'price': 3599,
                                     'commission_percent': 0.165, 'price_sale': 2997,
                                     'sale_qty': 1, 'sale_amount': 2997,
                                     'sale_discount': 8.28, 'sale_commission': 0.12,
                                     'sale_price_seller': 3005.16, 'return_sale': 0,
                                     'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0, 'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 47, 'product_id': 783790745,
                                     'product_name': 'Туба с чистящими салфетками, для LCD, TFT-мониторов, BURO BU-t ft',
                                     'offer_id': 'ruo6od',
                                     'barcode': '', 'price': 439, 'commission_percent': 0.225, 'price_sale': 440,
                                     'sale_qty': 1,
                                     'sale_amount': 440, 'sale_discount': 0, 'sale_commission': 99.78,
                                     'sale_price_seller': 340.22,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 48, 'product_id': 783811125, 'product_name': 'Топор пожарный',
                                     'offer_id': 'rtui1qd',
                                     'barcode': 'OZN1342394891', 'price': 649, 'commission_percent': 0.18,
                                     'price_sale': 596, 'sale_qty': 1,
                                     'sale_amount': 596, 'sale_discount': 0, 'sale_commission': 63.82,
                                     'sale_price_seller': 532.18,
                                     'return_sale': 0, 'return_qty': 0, 'return_amount': 0, 'return_discount': 0,
                                     'return_commission': 0,
                                     'return_price_seller': 0},
                                    {'row_number': 49, 'product_id': 783866667,
                                     'product_name': 'Термодатчик RTD-03.2 INDR комнатный',
                                     'offer_id': 'afgik87', 'barcode': '', 'price': 999, 'commission_percent': 0.165,
                                     'price_sale': 889,
                                     'sale_qty': 1, 'sale_amount': 889, 'sale_discount': 0, 'sale_commission': 54.84,
                                     'sale_price_seller': 834.16, 'return_sale': 0, 'return_qty': 0, 'return_amount': 0,
                                     'return_discount': 0,
                                     'return_commission': 0, 'return_price_seller': 0},
                                    {'row_number': 50, 'product_id': 783866667,
                                     'product_name': 'Термодатчик RTD-03.2 INDR комнатный',
                                     'offer_id': 'afgik87', 'barcode': '', 'price': 999, 'commission_percent': 0.165,
                                     'price_sale': 863,
                                     'sale_qty': 2, 'sale_amount': 1726, 'sale_discount': 0, 'sale_commission': 57.68,
                                     'sale_price_seller': 1668.32, 'return_sale': 863, 'return_qty': 1,
                                     'return_amount': 863,
                                     'return_discount': 0, 'return_commission': 28.84, 'return_price_seller': 834.16}]}}

import pandas as pd
import openpyxl

df = pd.DataFrame([[11, 21, 31], [12, 22, 32], [31, 32, 33]],
                  index=['one', 'two', 'three'], columns=['a', 'b', 'c'])

print(df)
